version: '3'
services:
    gutenberg:
        image: 'apfelwurm/docker-gutenberg:latest'
        env_file: .env
        ports:
        - "${APPPort}:80"
        - "${CUPSPort}:631"
        environment:
            DB_HDJANGO_SETTINGS_MODULEOST: '${DB_HDJANGO_SETTINGS_MODULEOST}'
            POSTGRES_SERVER: '${DBServer}'
            POSTGRES_PASSWORD: '${DBPassword}'
            POSTGRES_USER: '${DBUser}'
            POSTGRES_DB: '${DBName}'
            POSTGRES_PORT: '${DBPort}'
            REDIS_PORT: '${REDISPort}'
            REDIS_SERVER: '${REDISServer}'
            REDIS_PASSWORD: '${REDISPassword}'
            CUPS_PASSWORD: '${CUPSPassword}'
            GUTENBERG_SECRETKEY: '${GUTENBERGSecretKey}'
            SERVER_VHOST: '${SERVERVhost}'
            WAIT_HOSTS: 'gutenberg_psql:5432'
        networks:
            - gutenberg
        restart: always
        volumes:
            - gutenberg_storage_prints:/prints
            - gutenberg_storage_setup:/setup
            - gutenberg_storage_cups:/etc/cups
        # ports:
        #     - "${APPPort}:8081"
        depends_on:
            - gutenberg_psql
            - gutenberg_redis
    gutenberg_psql:
        image: 'postgres:latest'
        env_file: .env
        environment:
            POSTGRES_PASSWORD: '${DBPassword}'
            POSTGRES_USER: '${DBUser}'
            POSTGRES_DB: '${DBName}'
        volumes:
            - gutenberg_psql:/var/lib/postgresql/data
        networks:
            - gutenberg
        restart: always
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${DBUser} -d ${DBName}"]
          retries: 3
          timeout: 5s
    gutenberg_redis:
        image: redis:latest
        restart: always
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDISPassword}
        volumes:
        - gutenberg_cache:/data
        networks:
            - gutenberg

networks:
  gutenberg:
        driver: bridge
volumes:
  gutenberg_psql:
        driver: local
  gutenberg_storage_prints:
        driver: local
  gutenberg_storage_setup:
        driver: local
  gutenberg_storage_cups:
        driver: local
  gutenberg_cache:
        driver: local
