version: '3'
services:
    gutenberg:
        image: 'apfelwurm/docker-gutenberg:latest'
        env_file: .env
        expose:
            - "8081"
        environment:
            DB_HDJANGO_SETTINGS_MODULEOST: '${DB_HDJANGO_SETTINGS_MODULEOST}'
            POSTGRES_SERVER: '${DBServer}'
            POSTGRES_PASSWORD: '${DBPassword}'
            POSTGRES_USER: '${DBUser}'
            POSTGRES_DB: '${DBName}'
            POSTGRES_PORT: '${DBPort}'
            REDIS_PORT: '${REDISPort}'
            REDIS_SERVER: '${REDISServer}'
            REDIS_PASSWORD: '${REDISPassword}'
            GUTENBERG_SECRETKEY: '${GUTENBERGSecretKey}'
            VIRTUAL_HOST: "drucken.ams"
            VIRTUAL_PROTO: 'uwsgi'
            VIRTUAL_PORT: 8081
        networks:
            - gutenberg
        # ports:
        #     - "${APPPort}:8081"
        depends_on:
            - gutenberg_psql
            - gutenberg_redis
    gutenberg_psql:
        image: 'postgres:latest'
        env_file: .env
        environment:
            POSTGRES_PASSWORD: '${DBPassword}'
            POSTGRES_USER: '${DBUser}'
            POSTGRES_DB: '${DBName}'
        volumes:
            - gutenberg_psql:/var/lib/postgresql/data
        networks:
            - gutenberg
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${DBUser} -d ${DBName}"]
          retries: 3
          timeout: 5s
    gutenberg_redis:
        image: redis:latest
        restart: always
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDISPassword}
        volumes:
        - gutenberg_cache:/data
        networks:
            - gutenberg
    gutenberg_nginx-proxy:
        image: nginxproxy/nginx-proxy
        ports:
        - "${APPPort}:80"
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        depends_on:
            - gutenberg
        networks:
            - gutenberg



networks:
  gutenberg:
        driver: bridge
volumes:
  gutenberg_psql:
        driver: local
  gutenberg_storage:
        driver: local
  gutenberg_cache:
        driver: local
