name: Update Docker Hub Description

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows action to be run manually from the Actions tab

jobs:
  update-dockerhub-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update Docker HUB Description
        uses: peter-evans/dockerhub-description@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: apfelwurm/docker-gutenberg
          short-description: "Gutenberg office printer gateway docker image"
          readme-filepath: ./README.md
